/**
 * AI Companies Database — Expanded Edition
 * Comprehensive database of 90+ major AI companies from America, Asia, and Europe,
 * organized by category and region for the AI News Hub.
 * Focused on: AI tools, assistant agents, foundation models, AI infrastructure.
 */

export interface AICompany {
  id: string
  name: string
  region: 'us' | 'asia' | 'europe'
  country: string
  category: string
  specialty: string
  products: string[]
  searchKeywords: string[]
  founded: number
  logo: string // emoji/icon fallback
  website: string
}

export const AI_COMPANIES: AICompany[] = [
  // ══════════════════════════════════════════════════════
  // 🇺🇸 UNITED STATES — Foundation Models
  // ══════════════════════════════════════════════════════
  { id: 'openai', name: 'OpenAI', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'GPT series, DALL-E, Sora video generation, ChatGPT',
    products: ['GPT-4o', 'GPT-5', 'ChatGPT', 'DALL-E 3', 'Sora', 'Codex', 'Whisper', 'o1', 'o3', 'Operator'],
    searchKeywords: ['openai', 'gpt', 'chatgpt', 'dall-e', 'sora', 'o1', 'o3', 'sam altman', 'operator'],
    founded: 2015, logo: '🤖', website: 'https://openai.com' },
  { id: 'anthropic', name: 'Anthropic', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Claude AI assistant, AI safety research, computer use',
    products: ['Claude 4', 'Claude 3.5 Sonnet', 'Claude 3 Opus', 'Constitutional AI', 'Computer Use'],
    searchKeywords: ['anthropic', 'claude', 'dario amodei', 'ai safety', 'computer use'],
    founded: 2021, logo: '🧠', website: 'https://anthropic.com' },
  { id: 'google-deepmind', name: 'Google DeepMind', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Gemini, AlphaFold, AI research, AI agents',
    products: ['Gemini 2.5', 'Gemini Ultra', 'AlphaFold 3', 'Gemini Flash', 'Gemma', 'Project Astra', 'Veo'],
    searchKeywords: ['google deepmind', 'gemini', 'alphafold', 'google ai', 'sundar pichai', 'project astra', 'veo'],
    founded: 2010, logo: '💎', website: 'https://deepmind.google' },
  { id: 'meta-ai', name: 'Meta AI', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Llama open-source models, computer vision, AI agents',
    products: ['Llama 4', 'Llama 3', 'Emu', 'Segment Anything', 'Code Llama', 'Meta AI Assistant'],
    searchKeywords: ['meta ai', 'llama', 'mark zuckerberg', 'meta ai lab', 'yann lecun', 'meta agent'],
    founded: 2013, logo: '🔄', website: 'https://ai.meta.com' },
  { id: 'mistral', name: 'Mistral AI', region: 'europe', country: 'France', category: 'Foundation Models', specialty: 'Open-source LLMs, efficient AI models, Le Chat',
    products: ['Mistral Large', 'Mistral Medium', 'Mistral Small', 'Codestral', 'Mixtral', 'Le Chat', 'Mistral Agents'],
    searchKeywords: ['mistral', 'mistral ai', 'arthur Mensch', 'mixtral', 'le chat'],
    founded: 2023, logo: '🌬️', website: 'https://mistral.ai' },
  { id: 'xai', name: 'xAI', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Grok AI, understanding the universe, image generation',
    products: ['Grok 3', 'Grok 2', 'Grok Mini', 'Grok Image'],
    searchKeywords: ['xai', 'grok', 'elon musk', 'x ai'],
    founded: 2023, logo: '✖️', website: 'https://x.ai' },
  { id: 'cohere', name: 'Cohere', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Enterprise NLP, Command R models, AI agents',
    products: ['Command R+', 'Command R', 'Embed v3', 'Rerank v3', 'Cohere Agents'],
    searchKeywords: ['cohere', 'command r', 'enterprise ai', 'nlp'],
    founded: 2019, logo: '📝', website: 'https://cohere.com' },
  { id: 'ai21', name: 'AI21 Labs', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Jurassic models, AI writing tools, Jamba',
    products: ['Jamba', 'Jurassic-2', 'Wordtune', 'Mosaic'],
    searchKeywords: ['ai21', 'jamba', 'jurassic', 'wordtune'],
    founded: 2017, logo: '📖', website: 'https://ai21.com' },
  { id: 'amazon-anthropic', name: 'Amazon (AGI Lab)', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'Amazon Nova models, Bedrock, Alexa AI',
    products: ['Nova Pro', 'Nova Lite', 'Nova Premier', 'Amazon Bedrock', 'Amazon Q'],
    searchKeywords: ['amazon ai', 'nova model', 'amazon bedrock', 'amazon q', 'aws ai', 'andy jassy'],
    founded: 2023, logo: '📦', website: 'https://aws.amazon.com/ai' },
  { id: 'zoo', name: 'Zoo (formerly Sundar Pichai startup)', region: 'us', country: 'USA', category: 'Foundation Models', specialty: 'AI model training and research',
    products: ['Zoo Models'],
    searchKeywords: ['zoo ai', 'zoo models'],
    founded: 2024, logo: '🦁', website: 'https://zoo.com' },

  // ══════════════════════════════════════════════════════
  // 🇺🇸 UNITED STATES — AI Infrastructure & Hardware
  // ══════════════════════════════════════════════════════
  { id: 'nvidia', name: 'NVIDIA', region: 'us', country: 'USA', category: 'AI Hardware', specialty: 'GPU computing, CUDA, AI chips, NIM inference',
    products: ['H200', 'B200', 'Blackwell', 'CUDA', 'TensorRT', 'NIM', 'Nemo', 'DGX Cloud'],
    searchKeywords: ['nvidia', 'gpu', 'cuda', 'jen-hsun huang', 'blackwell', 'hopper', 'nim inference'],
    founded: 1993, logo: '🟢', website: 'https://nvidia.com' },
  { id: 'amd-ai', name: 'AMD (AI Division)', region: 'us', country: 'USA', category: 'AI Hardware', specialty: 'MI300 AI accelerators, ROCm, competing with NVIDIA',
    products: ['MI300X', 'MI325X', 'ROCm', 'Instinct', 'Ryzen AI'],
    searchKeywords: ['amd ai', 'mi300', 'rocm', 'lisa su', 'amd gpu ai'],
    founded: 1969, logo: '🔴', website: 'https://amd.com' },
  { id: 'databricks', name: 'Databricks', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'Data lakehouse, ML platform, MosaicML, DBRX',
    products: ['Databricks Lakehouse', 'MLflow', 'MosaicML', 'DBRX', 'Unity Catalog'],
    searchKeywords: ['databricks', 'mosaicml', 'dbrx', 'lakehouse', 'mlflow'],
    founded: 2013, logo: '🔥', website: 'https://databricks.com' },
  { id: 'huggingface', name: 'Hugging Face', region: 'us', country: 'USA', category: 'AI Platform', specialty: 'Open-source AI models hub, Transformers, Spaces',
    products: ['Transformers', 'Diffusers', 'Inference API', 'AutoTrain', 'Spaces', 'HuggingChat'],
    searchKeywords: ['hugging face', 'transformers', 'diffusers', 'open source ai', 'huggingchat'],
    founded: 2016, logo: '🤗', website: 'https://huggingface.co' },
  { id: 'scale-ai', name: 'Scale AI', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'AI data labeling, RLHF, government AI, data engine',
    products: ['Scale Data Engine', 'Scale Donovan', 'Scale Generative AI', 'Scale Spark'],
    searchKeywords: ['scale ai', 'data labeling', 'rlhf', 'alexandr wang', 'scale spark'],
    founded: 2016, logo: '📊', website: 'https://scale.com' },
  { id: 'palantir', name: 'Palantir', region: 'us', country: 'USA', category: 'Enterprise AI', specialty: 'AI-powered data analytics, AIP platform, government',
    products: ['AIP', 'Foundry', 'Gotham', 'Apollo'],
    searchKeywords: ['palantir', 'aip', 'foundry', 'alex karp'],
    founded: 2003, logo: '🔮', website: 'https://palantir.com' },
  { id: 'snowflake', name: 'Snowflake', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'Cloud data warehouse, Cortex AI, Arctic models',
    products: ['Snowflake Cortex', 'Arctic', 'Document AI', 'Snowpark'],
    searchKeywords: ['snowflake', 'cortex ai', 'arctic', 'data cloud'],
    founded: 2012, logo: '❄️', website: 'https://snowflake.com' },
  { id: 'anyscale', name: 'Anyscale', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'Ray framework, scalable AI compute, LLM serving',
    products: ['Ray', 'Anyscale Platform', 'LLM serving'],
    searchKeywords: ['anyscale', 'ray', 'scalable ai', 'robert nishihara'],
    founded: 2019, logo: '⚡', website: 'https://anyscale.com' },
  { id: 'coreweave', name: 'CoreWeave', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'GPU cloud computing for AI workloads',
    products: ['CoreWeave Cloud', 'GPU Instances', 'Kubernetes'],
    searchKeywords: ['coreweave', 'gpu cloud', 'ai infrastructure'],
    founded: 2017, logo: '☁️', website: 'https://coreweave.com' },
  { id: 'together-ai', name: 'Together AI', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'Cloud AI inference, open-source model hosting',
    products: ['Together Inference', 'Together Fine-tuning', 'RedPajama'],
    searchKeywords: ['together ai', 'together inference', 'redpajama', 'vipin vedula'],
    founded: 2022, logo: '🤝', website: 'https://together.ai' },
  { id: 'fireworks-ai', name: 'Fireworks AI', region: 'us', country: 'USA', category: 'AI Infrastructure', specialty: 'Fast AI inference platform, model serving',
    products: ['Fireworks Inference', 'Firefunction Calling', 'Vision Language Models'],
    searchKeywords: ['fireworks ai', 'fast inference', 'ai serving', 'lin qiao'],
    founded: 2022, logo: '🎆', website: 'https://fireworks.ai' },

  // ══════════════════════════════════════════════════════
  // 🇺🇸 UNITED STATES — AI Assistants & Agents
  // ══════════════════════════════════════════════════════
  { id: 'openai-copilot', name: 'Microsoft Copilot', region: 'us', country: 'USA', category: 'AI Assistant', specialty: 'AI productivity suite, Office integration, agents',
    products: ['Copilot Pro', 'Copilot for Microsoft 365', 'GitHub Copilot', 'Copilot Studio', 'Copilot Agents'],
    searchKeywords: ['microsoft copilot', 'github copilot', 'bing chat', 'satya nadella', 'copilot agent'],
    founded: 2023, logo: '🪟', website: 'https://copilot.microsoft.com' },
  { id: 'perplexity', name: 'Perplexity AI', region: 'us', country: 'USA', category: 'AI Search', specialty: 'AI-powered search engine, answer engine, deep research',
    products: ['Perplexity Pro', 'Perplexity Enterprise', 'pplx API', 'Deep Research', 'Sonar'],
    searchKeywords: ['perplexity', 'perplexity ai', 'ai search', 'aravind srinivas', 'deep research'],
    founded: 2022, logo: '🔍', website: 'https://perplexity.ai' },
  { id: 'adept-ai', name: 'Adept AI', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'AI agents that use software, ACT-1',
    products: ['ACT-1', 'Apt', 'Adept.ai'],
    searchKeywords: ['adept ai', 'ai agent', 'act-1'],
    founded: 2022, logo: '🤝', website: 'https://adept.ai' },
  { id: 'rabbit-ai', name: 'Rabbit', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'R1 AI agent device, LAM (Large Action Model)',
    products: ['Rabbit r1', 'LAM', 'rabbit hole'],
    searchKeywords: ['rabbit ai', 'rabbit r1', 'lam', 'large action model', 'jesse lyu'],
    founded: 2023, logo: '🐰', website: 'https://rabbit.tech' },
  { id: 'humane-ai', name: 'Humane', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'Ai Pin wearable AI device, ambient computing',
    products: ['Ai Pin', 'Cosmos OS', 'Humane AI'],
    searchKeywords: ['humane ai', 'ai pin', 'bethany bongiorno', 'cosmos'],
    founded: 2018, logo: '📌', website: 'https://humane.com' },
  { id: 'sierra-ai', name: 'Sierra AI', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'Enterprise AI agents for customer experience',
    products: ['Sierra Platform', 'AI Customer Agents'],
    searchKeywords: ['sierra ai', 'ai agent', 'bret taylor', 'customer experience ai'],
    founded: 2023, logo: '🏔️', website: 'https://sierra.ai' },
  { id: 'relevance-ai', name: 'Relevance AI', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'AI workforce agents, no-code AI agent builder',
    products: ['AI Workforce', 'Agent Builder', 'Relevance AI'],
    searchKeywords: ['relevance ai', 'ai workforce', 'no code ai agent'],
    founded: 2020, logo: '🎯', website: 'https://relevanceai.com' },

  // ══════════════════════════════════════════════════════
  // 🇺🇸 UNITED STATES — AI Developer Tools & Frameworks
  // ══════════════════════════════════════════════════════
  { id: 'langchain', name: 'LangChain', region: 'us', country: 'USA', category: 'AI Framework', specialty: 'LLM application framework, LangGraph, LangSmith',
    products: ['LangChain', 'LangGraph', 'LangSmith', 'LangServe', 'LangChain.js'],
    searchKeywords: ['langchain', 'langgraph', 'langsmith', 'llm framework', 'harrison chase'],
    founded: 2022, logo: '🔗', website: 'https://langchain.com' },
  { id: 'cursor', name: 'Cursor (Anysphere)', region: 'us', country: 'USA', category: 'AI Developer Tools', specialty: 'AI-first code editor, AI coding agent',
    products: ['Cursor Pro', 'Cursor Agent', 'Tab completion', 'Cursor Rules'],
    searchKeywords: ['cursor', 'cursor ai', 'anysphere', 'ai code editor', 'michael truell'],
    founded: 2022, logo: '↗️', website: 'https://cursor.com' },
  { id: 'vercel-ai', name: 'Vercel (AI SDK)', region: 'us', country: 'USA', category: 'AI Framework', specialty: 'AI SDK for building AI applications, v0',
    products: ['Vercel AI SDK', 'v0', 'ai chatbot sdk'],
    searchKeywords: ['vercel ai sdk', 'vercel ai', 'ai sdk', 'v0 dev'],
    founded: 2020, logo: '▲', website: 'https://vercel.com' },
  { id: 'windsurf', name: 'Windsurf (Codeium)', region: 'us', country: 'USA', category: 'AI Developer Tools', specialty: 'AI coding IDE, Cascade agent, Windsurf editor',
    products: ['Windsurf', 'Codeium', 'Cascade', 'Windsurf Editor'],
    searchKeywords: ['windsurf', 'codeium', 'cascade', 'ai coding ide'],
    founded: 2021, logo: '🏄', website: 'https://codeium.com' },
  { id: 'github-copilot', name: 'GitHub (Copilot)', region: 'us', country: 'USA', category: 'AI Developer Tools', specialty: 'AI pair programmer, Copilot Workspace, Actions',
    products: ['GitHub Copilot', 'Copilot Workspace', 'Copilot Actions', 'GitHub Models'],
    searchKeywords: ['github copilot', 'copilot workspace', 'thomas dohmk', 'github models'],
    founded: 2021, logo: '🐙', website: 'https://github.com/features/copilot' },
  { id: 'replit', name: 'Replit', region: 'us', country: 'USA', category: 'AI Developer Tools', specialty: 'AI-powered coding, Replit Agent, cloud IDE',
    products: ['Replit Agent', 'Ghostwriter', 'Replit Core', 'Deployments'],
    searchKeywords: ['replit', 'replit agent', 'ghostwriter', 'ai coding'],
    founded: 2016, logo: '⌨️', website: 'https://replit.com' },
  { id: 'supabase', name: 'Supabase', region: 'us', country: 'USA', category: 'AI Developer Tools', specialty: 'Open-source Firebase alternative, AI vector support',
    products: ['Supabase', 'pgvector', 'Edge Functions', 'Supabase AI'],
    searchKeywords: ['supabase', 'vector database', 'pgvector'],
    founded: 2020, logo: '⚡', website: 'https://supabase.com' },
  { id: 'resend', name: 'Resend', region: 'us', country: 'USA', category: 'AI Developer Tools', specialty: 'Email API for developers, AI email tools',
    products: ['Resend', 'React Email', 'Resend AI'],
    searchKeywords: ['resend', 'email api', 'react email'],
    founded: 2022, logo: '📧', website: 'https://resend.com' },
  { id: 'cursor-dev', name: 'Devin (Cognition AI)', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'Autonomous AI software engineer, Devin agent',
    products: ['Devin', 'Cognition AI'],
    searchKeywords: ['devin', 'cognition ai', 'ai software engineer', 'autonomous coding'],
    founded: 2023, logo: '🧑‍💻', website: 'https://cognition.ai' },

  // ══════════════════════════════════════════════════════
  // 🇺🇸 UNITED STATES — AI Video, Image & Audio
  // ══════════════════════════════════════════════════════
  { id: 'runway', name: 'Runway', region: 'us', country: 'USA', category: 'AI Video', specialty: 'AI video generation and editing',
    products: ['Gen-3 Alpha', 'Gen-2', 'RunwayML'],
    searchKeywords: ['runway', 'gen-3', 'ai video', 'video generation', 'runwayml'],
    founded: 2018, logo: '🎬', website: 'https://runwayml.com' },
  { id: 'midjourney', name: 'Midjourney', region: 'us', country: 'USA', category: 'AI Image', specialty: 'AI image generation through Discord/web',
    products: ['Midjourney v6', 'Midjourney v7', 'Niji'],
    searchKeywords: ['midjourney', 'ai art', 'image generation', 'david holz'],
    founded: 2021, logo: '🎨', website: 'https://midjourney.com' },
  { id: 'elevenlabs', name: 'ElevenLabs', region: 'us', country: 'USA', category: 'AI Audio', specialty: 'AI voice synthesis, text-to-speech, dubbing, music',
    products: ['ElevenLabs API', 'Voice Cloning', 'Dubbing', 'Voice Library', 'Eleven Music'],
    searchKeywords: ['elevenlabs', 'ai voice', 'text to speech', 'tts', 'voice cloning'],
    founded: 2022, logo: '🎙️', website: 'https://elevenlabs.io' },
  { id: 'pika-ai', name: 'Pika', region: 'us', country: 'USA', category: 'AI Video', specialty: 'AI video generation, Pika Labs, text-to-video',
    products: ['Pika 2.0', 'Pikaffects', 'Pika Labs'],
    searchKeywords: ['pika', 'pika ai', 'pika labs', 'text to video', 'demi guo'],
    founded: 2023, logo: '⚡', website: 'https://pika.art' },
  { id: 'stability-ai', name: 'Stability AI', region: 'europe', country: 'UK', category: 'AI Image', specialty: 'Stable Diffusion, generative AI, open-source models',
    products: ['Stable Diffusion 4', 'Stable Diffusion 3.5', 'Stable Cascade', 'Stable Audio'],
    searchKeywords: ['stability ai', 'stable diffusion', 'stable audio', 'emad mostaque'],
    founded: 2019, logo: '🖼️', website: 'https://stability.ai' },
  { id: 'suno-ai', name: 'Suno', region: 'us', country: 'USA', category: 'AI Audio', specialty: 'AI music generation, text-to-music, song creation',
    products: ['Suno v4', 'Suno Pro', 'Suno API'],
    searchKeywords: ['suno', 'suno ai', 'ai music', 'text to music', 'ai song'],
    founded: 2022, logo: '🎵', website: 'https://suno.com' },
  { id: 'udio-ai', name: 'Udio', region: 'us', country: 'USA', category: 'AI Audio', specialty: 'AI music generation, high-quality audio synthesis',
    products: ['Udio', 'Udio Pro'],
    searchKeywords: ['udio', 'udio ai', 'ai music generation'],
    founded: 2023, logo: '🎶', website: 'https://udio.com' },
  { id: 'kling-ai-us', name: 'HeyGen', region: 'us', country: 'USA', category: 'AI Video', specialty: 'AI video avatars, talking head videos, translation',
    products: ['HeyGen', 'Avatar SDK', 'Video Translate'],
    searchKeywords: ['heygen', 'ai avatar', 'talking head', 'video translate'],
    founded: 2020, logo: '🗣️', website: 'https://heygen.com' },
  { id: 'synthesia', name: 'Synthesia', region: 'us', country: 'USA', category: 'AI Video', specialty: 'AI video creation with virtual avatars for enterprise',
    products: ['Synthesia', 'AI Avatars', 'Video Platform'],
    searchKeywords: ['synthesia', 'ai avatar video', 'virtual avatar'],
    founded: 2017, logo: '📹', website: 'https://synthesia.io' },
  { id: 'ideogram-ai', name: 'Ideogram', region: 'us', country: 'USA', category: 'AI Image', specialty: 'AI image generation with accurate text rendering',
    products: ['Ideogram 2.0', 'Ideogram API'],
    searchKeywords: ['ideogram', 'ideogram ai', 'ai image text'],
    founded: 2022, logo: '💡', website: 'https://ideogram.ai' },

  // ══════════════════════════════════════════════════════
  // 🇺🇸 UNITED STATES — AI Search & Content
  // ══════════════════════════════════════════════════════
  { id: 'jasper', name: 'Jasper AI', region: 'us', country: 'USA', category: 'AI Content', specialty: 'AI marketing content generation',
    products: ['Jasper', 'Jasper for Business', 'Jasper Chat'],
    searchKeywords: ['jasper ai', 'ai content', 'ai marketing', 'ai writing'],
    founded: 2021, logo: '✍️', website: 'https://jasper.ai' },
  { id: 'copy-ai', name: 'Copy.ai', region: 'us', country: 'USA', category: 'AI Agent', specialty: 'AI go-to-market platform, GTM AI agents',
    products: ['Copy.ai', 'GTM AI', 'Workflows', 'Prebuilt Agents'],
    searchKeywords: ['copy ai', 'gtm ai', 'ai marketing agent'],
    founded: 2022, logo: '📋', website: 'https://copy.ai' },
  { id: 'character-ai', name: 'Character.ai', region: 'us', country: 'USA', category: 'AI Assistant', specialty: 'AI chatbot personalities, conversational AI',
    products: ['Character.ai', 'Character Creator', 'Group Chat'],
    searchKeywords: ['character ai', 'character.ai', 'ai chatbot', 'noam shazeer'],
    founded: 2021, logo: '🎭', website: 'https://character.ai' },
  { id: 'notion-ai', name: 'Notion AI', region: 'us', country: 'USA', category: 'AI Assistant', specialty: 'AI writing assistant in productivity workspace',
    products: ['Notion AI', 'Notion Q&A', 'Notion Calendar'],
    searchKeywords: ['notion ai', 'notion', 'productivity ai'],
    founded: 2016, logo: '📓', website: 'https://notion.so' },

  // ══════════════════════════════════════════════════════
  // 🇨🇳 CHINA — Foundation Models & Tech Giants
  // ══════════════════════════════════════════════════════
  { id: 'alibaba-cloud', name: 'Alibaba Cloud (Tongyi)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Qwen models, Tongyi Qianwen, cloud AI, ModelScope',
    products: ['Qwen 3', 'Qwen 2.5', 'Qwen-VL', 'Tongyi Qianwen', 'ModelScope', 'Qwen-Agent'],
    searchKeywords: ['alibaba ai', 'qwen', 'tongyi', 'qianwen', 'modelscope', 'damo academy', 'qwen agent'],
    founded: 2009, logo: '🟠', website: 'https://aliyun.com' },
  { id: 'baidu-ernie', name: 'Baidu (Ernie Bot)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Ernie/Wenxin models, autonomous driving, AI cloud',
    products: ['Ernie 4.5', 'Ernie Bot', 'Wenxin Yiyan', 'Apollo Go', 'Baidu AI Cloud'],
    searchKeywords: ['baidu ai', 'ernie', 'wenxin', 'ernie bot', 'robin li'],
    founded: 2000, logo: '🐶', website: 'https://yiyan.baidu.com' },
  { id: 'tencent-ai', name: 'Tencent AI Lab', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Hunyuan models, gaming AI, social AI, Tencent Cloud AI',
    products: ['Hunyuan-Large', 'Hunyuan-Pro', 'Tencent Hunyuan', 'Game AI', 'Yuanbao'],
    searchKeywords: ['tencent ai', 'hunyuan', 'tencent hunyuan', 'pony ma', 'yuanbao'],
    founded: 2016, logo: '🐧', website: 'https://ai.tencent.com' },
  { id: 'bytedance-doubao', name: 'ByteDance (Doubao)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Doubao/Skylark models, content AI, Jimeng, video AI',
    products: ['Doubao', 'Skylark', 'Doubao', 'Jimeng AI', 'Seed models', 'Coze'],
    searchKeywords: ['bytedance ai', 'doubao', 'skylark', 'jimeng', 'dreamina', 'seed', 'coze'],
    founded: 2012, logo: '🎵', website: 'https://bytedance.com' },
  { id: 'zhipu-ai', name: 'Zhipu AI (GLM)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'GLM series, ChatGLM, academic AI, AI agents',
    products: ['GLM-4', 'GLM-4V', 'ChatGLM', 'CogVideoX', 'CodeGeeX', 'AutoGLM', 'ZhiPu QingYan'],
    searchKeywords: ['zhipu ai', 'glm', 'chatglm', 'cogvideo', 'codegeex', '智谱清言', 'autoglm'],
    founded: 2019, logo: '🎓', website: 'https://zhipuai.cn' },
  { id: 'minimax', name: 'MiniMax', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'abab models, AI companions, video generation, Hailuo',
    products: ['abab 7', 'Hailuo Video', 'MiniMax API', 'Hailuo AI', 'Talkie', '星野'],
    searchKeywords: ['minimax', 'abab', 'hailuo', 'hailuo ai', 'yan junjie', 'talkie'],
    founded: 2021, logo: '🔘', website: 'https://minimaxi.com' },
  { id: 'moonshot-ai', name: 'Moonshot AI (Kimi)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Long-context LLMs, Kimi chatbot, AI assistant',
    products: ['Kimi k2', 'Moonshot-v1', 'Kimi Chat', 'Kimi Agent'],
    searchKeywords: ['moonshot ai', 'kimi', 'moonshot', '月之暗面', 'yang zhilin'],
    founded: 2023, logo: '🌙', website: 'https://kimi.moonshot.cn' },
  { id: 'deepseek-ai', name: 'DeepSeek', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'DeepSeek-V3, DeepSeek-R1 reasoning models, open-source',
    products: ['DeepSeek-V3', 'DeepSeek-R1', 'DeepSeek-Coder', 'Janus', 'DeepSeek-Prover'],
    searchKeywords: ['deepseek', 'deepseek r1', 'deepseek v3', 'deepseek coder', 'liang wenfeng'],
    founded: 2023, logo: '🐋', website: 'https://deepseek.com' },
  { id: 'stepfun', name: 'StepFun (Step-1)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Step series models, multi-modal AI',
    products: ['Step-2', 'Step-1V', 'Step-Audio', 'StepFun'],
    searchKeywords: ['stepfun', 'step ai', 'step-1', 'step-2'],
    founded: 2023, logo: '👣', website: 'https://stepfun.com' },
  { id: '01ai', name: '01.AI (Yi)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Yi series, large language models, Wanx image models',
    products: ['Yi-Lightning', 'Yi-Large', 'Yi-Vision', 'Yi-Coder', 'Wanx'],
    searchKeywords: ['01.ai', 'yi models', 'yi-lightning', 'kai-fu lee', '零一万物', 'wanx'],
    founded: 2023, logo: '01️⃣', website: 'https://01.ai' },
  { id: 'sensetime', name: 'SenseTime', region: 'asia', country: 'China', category: 'AI Infrastructure', specialty: 'Computer vision, AI chips, SenseNova models',
    products: ['SenseNova 5.0', 'SenseNova', 'SenseAuto', 'SenseCare'],
    searchKeywords: ['sensetime', 'sense nova', 'computer vision', 'ai chips'],
    founded: 2014, logo: '👁️', website: 'https://sensetime.com' },
  { id: 'baichuan', name: 'Baichuan AI', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Baichuan LLMs, Chinese language models',
    products: ['Baichuan 4', 'Baichuan 3', 'Baichuan API'],
    searchKeywords: ['baichuan', 'baichuan ai', '百川智能'],
    founded: 2023, logo: '🏔️', website: 'https://baichuan-ai.com' },
  { id: 'kimi-agent', name: 'iFlytek', region: 'asia', country: 'China', category: 'AI Assistant', specialty: 'Spark models, voice AI, translation, education AI',
    products: ['Spark 4.0', 'iFlytek Translator', 'SparkDesk', 'Hearing Aid'],
    searchKeywords: ['iflytek', 'spark', '科大讯飞', 'voice ai china'],
    founded: 1999, logo: '🗣️', website: 'https://iflytek.com' },
  { id: 'yitu-ai', name: 'Yitu Technology', region: 'asia', country: 'China', category: 'Enterprise AI', specialty: 'AI-powered healthcare, security, smart city',
    products: ['Yitu Healthcare', 'Yitu Security', 'CareCon'],
    searchKeywords: ['yitu', 'yitu technology', 'ai healthcare china'],
    founded: 2012, logo: '🏥', website: 'https://yitu-tech.com' },
  { id: 'zijian-ai', name: 'Zijian AI', region: 'asia', country: 'China', category: 'AI Agent', specialty: 'AI coding agent, AutoDev, software engineering AI',
    products: ['Zijian Agent', 'AutoDev', 'Zijian'],
    searchKeywords: ['zijian ai', 'autoagent', 'ai coding agent china'],
    founded: 2024, logo: '🔧', website: 'https://zijian.ai' },
  { id: 'kling-ai', name: 'Kuaishou (Kling)', region: 'asia', country: 'China', category: 'AI Video', specialty: 'Kling AI video generation, short video AI',
    products: ['Kling 1.6', 'Kling AI', 'Kling Web'],
    searchKeywords: ['kling', 'kling ai', 'kuaishou ai', 'ai video china'],
    founded: 2024, logo: '🎥', website: 'https://kling.ai' },
  { id: 'silicon-flow', name: 'SiliconFlow', region: 'asia', country: 'China', category: 'AI Infrastructure', specialty: 'AI inference cloud, model serving platform',
    products: ['SiliconCloud', 'Model Repository', 'Inference API'],
    searchKeywords: ['siliconflow', 'silicon cloud', 'ai inference china'],
    founded: 2023, logo: '🫧', website: 'https://siliconflow.cn' },
  { id: 'doubao-ai', name: 'Volcano Engine (Doubao)', region: 'asia', country: 'China', category: 'Foundation Models', specialty: 'Doubao models, ByteDance cloud AI platform',
    products: ['Doubao Pro', 'Doubao Lite', 'Volcano Engine AI', 'Ark Runtime'],
    searchKeywords: ['volcano engine', 'doubao', '火山引擎', 'ark runtime'],
    founded: 2019, logo: '🌋', website: 'https://volcengine.com' },

  // ══════════════════════════════════════════════════════
  // 🇮🇳 INDIA — AI Companies
  // ══════════════════════════════════════════════════════
  { id: 'krutrim-ai', name: 'Krutrim (Ola AI)', region: 'asia', country: 'India', category: 'Foundation Models', specialty: 'India multilingual LLM, Krutrim AI assistant',
    products: ['Krutrim', 'Krutrim Pro', 'Krutrim Cloud'],
    searchKeywords: ['krutrim', 'ola ai', 'india llm', 'bhavish aggarwal'],
    founded: 2023, logo: '🇮🇳', website: 'https://krutrim.ai' },
  { id: 'sarvam-ai', name: 'Sarvam AI', region: 'asia', country: 'India', category: 'Foundation Models', specialty: 'Indian language AI models, enterprise AI solutions',
    products: ['Sarvam 1', 'Sarvam Speech', 'Sarvam Translation'],
    searchKeywords: ['sarvam ai', 'india ai', 'indian language model'],
    founded: 2023, logo: '🗣️', website: 'https://sarvam.ai' },
  { id: 'fluid-ai', name: 'Fluid AI', region: 'asia', country: 'India', category: 'Enterprise AI', specialty: 'Enterprise AI solutions, conversational AI, banking AI',
    products: ['Fluid AI Platform', 'AI Chatbots'],
    searchKeywords: ['fluid ai', 'enterprise ai india', 'conversational ai'],
    founded: 2016, logo: '💧', website: 'https://fluid.ai' },
  { id: 'yellow-ai', name: 'Yellow.ai', region: 'asia', country: 'India', category: 'AI Agent', specialty: 'Conversational AI agents, enterprise chatbots, automation',
    products: ['Yellow.ai Platform', 'YellowG Agent', 'Conversational CX'],
    searchKeywords: ['yellow ai', 'conversational ai', 'enterprise chatbot india'],
    founded: 2016, logo: '🟡', website: 'https://yellow.ai' },
  { id: 'haptik-ai', name: 'Haptik AI (Jio)', region: 'asia', country: 'India', category: 'AI Agent', specialty: 'AI chatbot platform, enterprise conversational AI',
    products: ['Haptik', 'AIRA', 'Gupshup Integration'],
    searchKeywords: ['haptik', 'jio ai', 'ai chatbot india'],
    founded: 2013, logo: '💬', website: 'https://haptik.ai' },
  { id: 'wysa-ai', name: 'Wysa', region: 'asia', country: 'India', category: 'AI Assistant', specialty: 'AI mental health chatbot, therapy assistant',
    products: ['Wysa', 'Wysa for Enterprise', 'Wysa AI'],
    searchKeywords: ['wysa', 'ai mental health', 'ai therapy chatbot'],
    founded: 2015, logo: '💚', website: 'https://wysa.com' },
  { id: 'machinedalal', name: 'Machin.ai', region: 'asia', country: 'India', category: 'AI Developer Tools', specialty: 'AI automation tools, workflow AI',
    products: ['Machin.ai Platform'],
    searchKeywords: ['machin ai', 'ai automation india'],
    founded: 2022, logo: '⚙️', website: 'https://machin.ai' },

  // ══════════════════════════════════════════════════════
  // 🇯🇵 JAPAN — AI Companies
  // ══════════════════════════════════════════════════════
  { id: 'sakura-ai', name: 'Sakura AI', region: 'asia', country: 'Japan', category: 'Foundation Models', specialty: 'Japanese-optimized LLMs, open-source',
    products: ['Sakura-9B', 'Sakura-14B', 'Sakura-34B'],
    searchKeywords: ['sakura ai', 'japanese llm', 'sakura model'],
    founded: 2024, logo: '🌸', website: 'https://sakura-ai.com' },
  { id: 'rinna', name: 'Rinna', region: 'asia', country: 'Japan', category: 'Foundation Models', specialty: 'Japanese language models, conversational AI',
    products: ['Rinna-3.6B', 'Rinna-13B'],
    searchKeywords: ['rinna', 'japanese ai', 'rinna model'],
    founded: 2020, logo: '🗣️', website: 'https://rinna.co.jp' },
  { id: 'preferred-networks', name: 'Preferred Networks', region: 'asia', country: 'Japan', category: 'AI Research', specialty: 'Deep learning, industrial AI, robotics',
    products: ['MN-3', 'Plaide', 'PFC'],
    searchKeywords: ['preferred networks', 'pfn', 'mn-3'],
    founded: 2014, logo: '🏋️', website: 'https://preferred-networks.jp' },
  { id: 'sony-ai', name: 'Sony AI', region: 'asia', country: 'Japan', category: 'AI Research', specialty: 'AI gaming, sensing, gastronomy',
    products: ['Gaming AI', 'Gran Turismo Sophy', 'AI sensing'],
    searchKeywords: ['sony ai', 'sophy', 'gran turismo ai'],
    founded: 2020, logo: '🎮', website: 'https://ai.sony' },
  { id: 'lightblue-ai', name: 'Lightblue', region: 'asia', country: 'Japan', category: 'AI Agent', specialty: 'AI workflow automation, enterprise AI agents in Japan',
    products: ['Lightblue Platform', 'Workflow AI'],
    searchKeywords: ['lightblue', 'japan ai agent', 'ai workflow japan'],
    founded: 2018, logo: '🔵', website: 'https://lightblue.co.jp' },

  // ══════════════════════════════════════════════════════
  // 🇰🇷 SOUTH KOREA — AI Companies
  // ══════════════════════════════════════════════════════
  { id: 'samsung-ai', name: 'Samsung AI', region: 'asia', country: 'South Korea', category: 'AI Research', specialty: 'Samsung Gauss, Galaxy AI, semiconductor AI',
    products: ['Samsung Gauss', 'Galaxy AI', 'Gauss Code', 'Gauss Language'],
    searchKeywords: ['samsung ai', 'samsung gauss', 'galaxy ai'],
    founded: 2022, logo: '📱', website: 'https://ai.samsung.com' },
  { id: 'naver-ai', name: 'Naver (HyperCLOVA)', region: 'asia', country: 'South Korea', category: 'Foundation Models', specialty: 'HyperCLOVA X, Naver AI, Korean AI platform',
    products: ['HyperCLOVA X', 'CLOVA X', 'Naver AI', 'Naver Bot'],
    searchKeywords: ['naver ai', 'hyperclova', 'clova', 'korean ai'],
    founded: 2022, logo: '🟢', website: 'https://naver.com' },
  { id: 'kakao-ai', name: 'Kakao Enterprise', region: 'asia', country: 'South Korea', category: 'AI Platform', specialty: 'Korean AI, KoGPT, Mi:da, Kanana',
    products: ['KoGPT', 'Mi:da', 'Kanana', 'Kakao AI'],
    searchKeywords: ['kakao ai', 'kogpt', 'korean ai', 'kanana'],
    founded: 2018, logo: '💬', website: 'https://kakaoenterprise.com' },
  { id: 'upstage-ai', name: 'Upstage AI', region: 'asia', country: 'South Korea', category: 'Foundation Models', specialty: 'Solar LLM, enterprise AI solutions, document AI',
    products: ['Solar Mini', 'Solar Pro', 'Document AI', 'SOLAR'],
    searchKeywords: ['upstage', 'solar llm', 'korean ai startup'],
    founded: 2022, logo: '⬆️', website: 'https://upstage.ai' },
  { id: 'lg-ai', name: 'LG AI Research', region: 'asia', country: 'South Korea', category: 'AI Research', specialty: 'EXAONE models, multi-modal AI',
    products: ['EXAONE 3.5', 'EXAONE 3.0'],
    searchKeywords: ['lg ai', 'exaone', 'lg ai research'],
    founded: 2020, logo: '🧪', website: 'https://lg-ai.co.kr' },
  { id: 'comcom-ai', name: 'Comcom AI', region: 'asia', country: 'South Korea', category: 'AI Agent', specialty: 'AI agents for enterprise automation in Korea',
    products: ['Comcom Agent Platform'],
    searchKeywords: ['comcom ai', 'korea ai agent'],
    founded: 2020, logo: '🤖', website: 'https://comcom.ai' },

  // ══════════════════════════════════════════════════════
  // 🇸🇬🇦🇪🇮🇩 ASIA — Other Major AI Companies
  // ══════════════════════════════════════════════════════
  { id: 'sea-ai-lab', name: 'Sea Group (Sea AI Lab)', region: 'asia', country: 'Singapore', category: 'AI Research', specialty: 'Southeast Asian AI, multilingual NLP, SeaLLM',
    products: ['SeaLLM', 'Sea AI Lab models'],
    searchKeywords: ['sea ai lab', 'seallm', 'southeast asia ai'],
    founded: 2020, logo: '🌊', website: 'https://sea.com' },
  { id: 'g42-uae', name: 'G42 (UAE)', region: 'asia', country: 'UAE', category: 'Foundation Models', specialty: 'Jais Arabic LLM, national AI initiatives, Falcon models',
    products: ['Jais 2', 'NANDA', 'ClimateAI', 'Falcon'],
    searchKeywords: ['g42', 'jais', 'uae ai', 'arabic llm', 'falcon model'],
    founded: 2018, logo: '🏗️', website: 'https://g42.ai' },
  { id: 'wiz-ai', name: 'Wiz AI', region: 'asia', country: 'Singapore', category: 'Enterprise AI', specialty: 'Conversational AI for enterprise in Asia',
    products: ['Wiz AI Platform', 'Voice AI'],
    searchKeywords: ['wiz ai', 'singapore ai'],
    founded: 2019, logo: '🧙', website: 'https://wiz.ai' },
  { id: 'indonesia-ai', name: 'GoTo (Gojek AI)', region: 'asia', country: 'Indonesia', category: 'AI Platform', specialty: 'Southeast Asia AI, ride-hailing AI, fintech AI',
    products: ['Gojek AI', 'GoPay AI', 'GoTo AI Platform'],
    searchKeywords: ['goto ai', 'gojek ai', 'indonesia ai', 'southeast asia ai'],
    founded: 2021, logo: '🇮🇩', website: 'https://goto.com' },

  // ══════════════════════════════════════════════════════
  // 🇪🇺 EUROPE — AI Companies
  // ══════════════════════════════════════════════════════
  { id: 'aleph-alpha', name: 'Aleph Alpha', region: 'europe', country: 'Germany', category: 'Foundation Models', specialty: 'European sovereign AI, Luminous models, Pharia',
    products: ['Luminous', 'Pharia', 'PhariaAgent'],
    searchKeywords: ['aleph alpha', 'european ai', 'luminous', 'pharia'],
    founded: 2019, logo: '🔤', website: 'https://aleph-alpha.com' },
  { id: 'mistral-eu', name: 'Mistral AI (EU)', region: 'europe', country: 'France', category: 'Foundation Models', specialty: 'European AI champion, open-source models',
    products: ['Mistral Large', 'Mixtral', 'Codestral', 'Mistral Small'],
    searchKeywords: ['mistral ai', 'french ai', 'european llm'],
    founded: 2023, logo: '🌬️', website: 'https://mistral.ai' },
]

/** Category groups for the news page */
export const COMPANY_CATEGORIES = [
  { key: 'all', label: 'All Companies' },
  { key: 'us', label: '🇺🇸 American Companies' },
  { key: 'asia', label: '🌏 Asian Companies' },
  { key: 'europe', label: '🇪🇺 European Companies' },
  { key: 'Foundation Models', label: 'Foundation Models' },
  { key: 'AI Infrastructure', label: 'AI Infrastructure' },
  { key: 'AI Platform', label: 'AI Platforms' },
  { key: 'AI Agent', label: 'AI Agents' },
  { key: 'AI Assistant', label: 'AI Assistants' },
  { key: 'AI Video', label: 'AI Video' },
  { key: 'AI Image', label: 'AI Image' },
  { key: 'AI Audio', label: 'AI Audio' },
  { key: 'Enterprise AI', label: 'Enterprise AI' },
  { key: 'AI Framework', label: 'AI Frameworks' },
  { key: 'AI Developer Tools', label: 'Dev Tools' },
  { key: 'AI Hardware', label: 'AI Hardware' },
  { key: 'AI Search', label: 'AI Search' },
  { key: 'AI Research', label: 'AI Research' },
  { key: 'AI Content', label: 'AI Content' },
]

/** Get companies by filter */
export function getCompaniesByFilter(filter: string): AICompany[] {
  if (filter === 'all') return AI_COMPANIES
  return AI_COMPANIES.filter(c =>
    c.region === filter ||
    c.category === filter
  )
}

/** Match news text to relevant companies */
export function matchCompanies(text: string): AICompany[] {
  const lower = text.toLowerCase()
  return AI_COMPANIES.filter(c => {
    return c.searchKeywords.some(kw => lower.includes(kw.toLowerCase()))
  })
}

/** Smart search queries for news fetching — organized by focus area
 *  Expanded to 50+ queries for comprehensive daily coverage
 */
export const NEWS_SEARCH_QUERIES = [
  // ═══ Foundation Model Updates (12 queries) ═══
  'GPT OpenAI latest news update 2026',
  'Claude Anthropic new features release 2026',
  'Gemini Google AI latest update 2026',
  'Llama Meta AI open source model release 2026',
  'DeepSeek new model announcement 2026',
  'Qwen Alibaba Tongyi latest release 2026',
  'Mistral AI model update release 2026',
  'xAI Grok new features update 2026',
  'new AI model benchmark release leaderboard 2026',
  'AI research paper breakthrough 2026',
  'best open source AI models release 2026',
  'AI model comparison benchmark results 2026',

  // ═══ AI Agents & Assistants (10 queries) ═══
  'AI agents autonomous tools latest 2026',
  'AI assistant chatbot new release update 2026',
  'AI copilot developer tools new release 2026',
  'AI coding assistant new features 2026',
  'AI automation workflow tools update 2026',
  'AI agent platform enterprise release 2026',
  'autonomous AI software engineer tools 2026',
  'AI personal assistant app launch 2026',
  'AI agent framework LangGraph CrewAI AutoGen 2026',
  'AI assistant API integration tools 2026',

  // ═══ AI Tools & Developer Products (8 queries) ═══
  'Cursor AI code editor new features 2026',
  'AI IDE coding tools Windsurf Copilot update 2026',
  'AI development tools new release framework 2026',
  'AI API inference platform new tools 2026',
  'AI vector database RAG tools release 2026',
  'AI prompt engineering tools new features 2026',
  'AI low-code no-code platform update 2026',
  'AI testing debugging tools developer release 2026',

  // ═══ AI Video & Image Generation (6 queries) ═══
  'AI video generation new model Sora Runway Kling 2026',
  'AI image generation Midjourney DALL-E Stable Diffusion update',
  'AI music and audio generation new tools Suno Udio 2026',
  'AI avatar video creation tools HeyGen Synthesia 2026',
  'AI design creative tools new release 2026',
  'AI 3D generation modeling tools update 2026',

  // ═══ Asian AI Companies (8 queries) ═══
  'Chinese AI companies latest news update 2026',
  'DeepSeek Qwen Zhipu model release news 2026',
  'Japan Korea AI startup new release 2026',
  'Asia AI technology news breakthrough 2026',
  'India AI companies startup funding 2026',
  'Singapore UAE AI development news 2026',
  'Alibaba Tencent ByteDance AI product launch 2026',
  'Kling Hailuo Jimeng AI video generation China 2026',

  // ═══ Enterprise, Hardware & Policy (6 queries) ═══
  'enterprise AI platform new features 2026',
  'AI chip GPU NVIDIA AMD latest news 2026',
  'AI regulation policy news 2026',
  'AI startup funding investment news 2026',
  'AI infrastructure cloud computing news 2026',
  'AI safety alignment research news 2026',
]
