'use client'

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { OutputItem } from '@/lib/store'
import { formatPValue } from '@/lib/stats'

interface ReportOptions {
  title?: string
  author?: string
  projectName?: string
  outputs: OutputItem[]
  variables?: { name: string; type: string; label: string }[]
  data?: Record<string, any[]>
}

export function generateEnhancedReport(options: ReportOptions) {
  const { title, author = 'TheOneWayGDA', projectName, outputs, variables = [], data = {} } = options
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const doc = new jsPDF('p', 'mm', 'a4') as any
  const pw = doc.internal.pageSize.getWidth()
  const ph = doc.internal.pageSize.getHeight()
  const ml = 25
  const mr = 20
  const cw = pw - ml - mr
  let pageNum = 0

  const addPage = () => {
    if (pageNum > 0) doc.addPage()
    pageNum++
  }

  const runningTitle = (title || 'Statistical Report').slice(0, 40)

  const addFooter = () => {
    doc.setPage(pageNum)
    // Running header
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(runningTitle, pw - mr, 12, { align: 'right' })
    // Page number
    doc.text(`Page ${pageNum}`, pw / 2, ph - 10, { align: 'center' })
    // Generated by
    doc.setFontSize(7)
    doc.text('Generated by TheOneWayGDA', ml, ph - 10)
  }

  const addPageAndFooter = () => {
    addPage()
    addFooter()
  }

  const checkPage = (needed: number) => {
    if (doc.internal.getNumberOfPages() === 0 || doc.getY() + needed > ph - 20) {
      addPageAndFooter()
      return true
    }
    return false
  }

  const ensureSpace = (h: number) => {
    if (doc.getY() + h > ph - 20) {
      addPageAndFooter()
      doc.setY(20)
    }
  }

  // ═══════════════════════════════════════
  // COVER PAGE
  // ═══════════════════════════════════════
  addPage()

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  const reportTitle = title || 'Statistical Analysis Report'
  const titleLines = doc.splitTextToSize(reportTitle, pw - 80)
  let yPos = 80
  titleLines.forEach((line: string) => {
    doc.text(line, pw / 2, yPos, { align: 'center' })
    yPos += 14
  })

  yPos += 8
  // Decorative line
  doc.setDrawColor(37, 99, 235)
  doc.setLineWidth(0.8)
  doc.line(pw / 2 - 40, yPos, pw / 2 + 40, yPos)
  yPos += 15

  if (projectName) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(16)
    doc.text(projectName, pw / 2, yPos, { align: 'center' })
    yPos += 12
  }

  yPos += 20
  doc.setFontSize(13)
  doc.setTextColor(80)
  doc.text(author, pw / 2, yPos, { align: 'center' })
  yPos += 10

  doc.setFontSize(11)
  const today = new Date()
  doc.text(today.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pw / 2, yPos, { align: 'center' })

  yPos += 40
  doc.setFontSize(9)
  doc.setTextColor(150)
  doc.text('Generated by TheOneWayGDA Statistical Analysis Platform', pw / 2, yPos, { align: 'center' })
  doc.text('https://theonewaygda.app', pw / 2, yPos + 6, { align: 'center' })

  // ═══════════════════════════════════════
  // TABLE OF CONTENTS
  // ═══════════════════════════════════════
  addPageAndFooter()
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.text('Table of Contents', ml, 20)

  yPos = 32
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  // Add methods section
  const tocItems: { label: string; page: number }[] = []

  // Count pages for each output to estimate TOC page numbers
  let estPage = 3 // Start after TOC

  outputs.forEach((output, idx) => {
    const isTable = output.type === 'table' && output.content?.rows
    const rows = isTable ? (output.content.rows as string[][]).length : 0
    estPage += Math.max(1, Math.ceil(rows / 30))
    tocItems.push({ label: output.title, page: estPage })
  })

  tocItems.forEach((item) => {
    const labelWidth = doc.getTextWidth(item.label)
    const dots = '.'.repeat(Math.max(1, Math.floor((cw - labelWidth - 20) / doc.getTextWidth('.'))))
    doc.text(`${item.label} ${dots} ${item.page}`, ml, yPos)
    yPos += 7
    if (yPos > ph - 30) {
      addPageAndFooter()
      yPos = 25
    }
  })

  // ═══════════════════════════════════════
  // METHOD SECTION
  // ═══════════════════════════════════════
  addPageAndFooter()
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Method', ml, 20)
  yPos = 28

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(50)

  const totalN = variables.length > 0 && data[variables[0]?.name]
    ? (data[variables[0].name] as any[]).filter(v => v !== '' && v !== null && v !== undefined).length
    : 0

  const methodText = [
    `This report presents the results of a statistical analysis conducted using TheOneWayGDA platform. The analysis included ${variables.length} variable${variables.length !== 1 ? 's' : ''} with a total sample size of N = ${totalN}.`,
    '',
    'Statistical significance was evaluated at the alpha = .05 level. All statistical tests were two-tailed unless otherwise specified. Effect sizes are reported following established conventions (Cohen, 1988).',
    '',
    `The following analyses were performed: ${outputs.filter(o => o.type === 'table').length} statistical analyses with corresponding visualizations.`,
  ]

  methodText.forEach((line) => {
    const lines = doc.splitTextToSize(line, cw)
    doc.text(lines, ml, yPos)
    yPos += lines.length * 5 + 2
    if (yPos > ph - 30) {
      addPageAndFooter()
      yPos = 25
    }
  })

  // ═══════════════════════════════════════
  // DATA DICTIONARY
  // ═══════════════════════════════════════
  if (variables.length > 0) {
    yPos += 10
    ensureSpace(25)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text('Data Dictionary', ml, doc.getY())
    doc.setFontSize(10)
    yPos = doc.getY() + 8

    autoTable(doc, {
      startY: yPos,
      margin: { left: ml, right: mr },
      head: [['Variable', 'Type', 'Label']],
      body: variables.map(v => [v.name, v.type, v.label || v.name]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      theme: 'grid',
    })
  }

  // ═══════════════════════════════════════
  // OUTPUTS
  // ═══════════════════════════════════════
  let outputNum = 0
  for (const output of outputs) {
    addPageAndFooter()
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(0)
    const outTitle = `${++outputNum}. ${output.title}`
    doc.text(doc.splitTextToSize(outTitle, cw), ml, 20)
    yPos = doc.getY() + 8

    // Timestamp
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(new Date(output.timestamp).toLocaleString(), ml, yPos)
    yPos += 8
    doc.setTextColor(0)

    if (output.type === 'table' && output.content?.headers && output.content?.rows) {
      const { headers, rows } = output.content as { headers: string[]; rows: string[][] }

      // Check if this looks like a statistical test result (2-column Statistic/Value format)
      const isStatTable = headers.length === 2 && headers[0]?.toLowerCase().includes('statistic')

      autoTable(doc, {
        startY: yPos,
        margin: { left: ml, right: mr },
        head: [headers.map(h => h)],
        body: rows.map((row, idx) => [String(idx + 1), ...row.map(c => String(c))]),
        styles: {
          fontSize: 9,
          cellPadding: 3,
          fontStyle: 'normal',
        },
        headStyles: {
          fillColor: [37, 99, 235],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 9,
          halign: 'left',
        },
        alternateRowStyles: {
          fillColor: [245, 247, 250],
        },
        columnStyles: isStatTable
          ? { 0: { cellWidth: 15, fontStyle: 'normal' }, 1: { cellWidth: cw - 50, halign: 'left' }, 2: { halign: 'left' } }
          : {},
        theme: 'grid',
        didDrawPage: (data) => {
          yPos = data.cursor?.y || 20
        },
      })

      // Add interpretation for key statistical results
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(9)
      doc.setTextColor(100)
      yPos = doc.getY() + 5

      if (output.title.includes('Correlation') && rows.length > 0) {
        const r = parseFloat(rows[0]?.[1] || '0')
        const n = parseFloat(rows[rows.length - 1]?.[1] || '0')
        if (!isNaN(r) && !isNaN(n)) {
          const strength = Math.abs(r) > 0.7 ? 'strong' : Math.abs(r) > 0.4 ? 'moderate' : Math.abs(r) > 0.2 ? 'weak' : 'very weak'
          const direction = r > 0 ? 'positive' : 'negative'
          const lines = doc.splitTextToSize(
            `Note: A ${strength} ${direction} correlation was observed, r(${Math.round(n)}) = ${r.toFixed(3)}.`,
            cw
          )
          doc.text(lines, ml, yPos)
          yPos += lines.length * 5 + 3
        }
      }
    } else if (output.type === 'text') {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.setTextColor(40)
      const textLines = doc.splitTextToSize(String(output.content || ''), cw)
      doc.text(textLines, ml, yPos)
      yPos += textLines.length * 5 + 3
    } else if (output.type === 'chart') {
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(10)
      doc.setTextColor(100)
      const c = output.content
      if (c?.dv && c?.iv) {
        const lines = doc.splitTextToSize(
          `Scatter Plot: ${c.dv} vs ${c.iv}${c.slope != null ? `\nRegression: ${c.dv} = ${c.intercept?.toFixed(2)} + ${c.slope.toFixed(2)} x ${c.iv}${c.r2 != null ? `, R-squared = ${c.r2.toFixed(3)}` : ''}` : ''}`,
          cw
        )
        doc.text(lines, ml, yPos)
        yPos += lines.length * 5 + 3
      } else if (c?.title) {
        const lines = doc.splitTextToSize(
          `Chart: ${c.title} (Interactive visualization available in the application)`,
          cw
        )
        doc.text(lines, ml, yPos)
      }
    }
  }

  // ═══════════════════════════════════════
  // ADD FOOTERS TO ALL PAGES
  // ═══════════════════════════════════════
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    // Running header (skip cover)
    if (i > 1) {
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(8)
      doc.setTextColor(150)
      doc.text(runningTitle, pw - mr, 12, { align: 'right' })
    }
    // Page number
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`${i} of ${totalPages}`, pw / 2, ph - 10, { align: 'center' })
    // Generated by
    doc.text('Generated by TheOneWayGDA', ml, ph - 10)
  }

  // Download
  doc.save(`${(projectName || 'report').replace(/[^a-zA-Z0-9]/g, '_')}_enhanced_report.pdf`)
}

export function generateQuickEnhancedReport(outputs: OutputItem[], projectName?: string, variables?: any[], data?: Record<string, any[]>) {
  generateEnhancedReport({
    title: 'Statistical Analysis Report',
    author: 'TheOneWayGDA',
    outputs,
    projectName,
    variables,
    data,
  })
}
