'use client'

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { OutputItem } from '@/lib/store'
import { formatPValue } from '@/lib/stats'

interface ReportOptions {
  title?: string
  author?: string
  outputs: OutputItem[]
  projectName?: string
}

export function generatePDFReport(options: ReportOptions) {
  const { title, author = 'TheOneWayGDAGDA', outputs, projectName } = options
  const doc = new jsPDF('p', 'mm', 'a4')
  const pageWidth = doc.internal.pageSize.getWidth()

  // ─── Title Page (APA 7th style) ───
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  const reportTitle = title || `Statistical Analysis Report`
  const textLines = doc.splitTextToSize(reportTitle, pageWidth - 60)
  let yPos = 80
  textLines.forEach((line: string) => {
    doc.text(line, pageWidth / 2, yPos, { align: 'center' })
    yPos += 12
  })

  yPos += 10
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(14)
  if (projectName) {
    doc.text(projectName, pageWidth / 2, yPos, { align: 'center' })
    yPos += 10
  }

  yPos += 10
  doc.setFontSize(12)
  doc.text(author, pageWidth / 2, yPos, { align: 'center' })
  yPos += 8
  doc.setFontSize(11)
  const today = new Date()
  const dateStr = today.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  doc.text(dateStr, pageWidth / 2, yPos, { align: 'center' })

  yPos += 30
  doc.setFontSize(10)
  doc.setTextColor(120)
  doc.text('Generated by TheOneWayGDAGDA Statistical Workspace', pageWidth / 2, yPos, { align: 'center' })

  // ─── Content Pages ───
  let pageNum = 2

  for (const output of outputs) {
    doc.addPage()
    pageNum++

    // Page header
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text(`Page ${pageNum - 1}`, pageWidth - 15, 12, { align: 'right' })

    // Output title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(0)
    const titleLines = doc.splitTextToSize(output.title, pageWidth - 40)
    doc.text(titleLines, 20, 25)
    let currentY = 25 + titleLines.length * 7 + 5

    // Timestamp
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text(new Date(output.timestamp).toLocaleString(), 20, currentY)
    currentY += 10

    // Content
    if (output.type === 'table' && output.content?.headers && output.content?.rows) {
      const tableData = output.content.rows.map((row: string[], idx: number) =>
        [String(idx + 1), ...row.map((cell: string) => String(cell))]
      )

      autoTable(doc, {
        startY: currentY,
        head: [['#', ...output.content.headers]],
        body: tableData,
        margin: { left: 15, right: 15 },
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        headStyles: {
          fillColor: [59, 130, 246],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 9,
        },
        alternateRowStyles: {
          fillColor: [245, 247, 250],
        },
        theme: 'grid',
      })
    } else if (output.type === 'text') {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(40)
      const textLines = doc.splitTextToSize(String(output.content || ''), pageWidth - 40)
      doc.text(textLines, 20, currentY)
    } else if (output.type === 'chart') {
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(10)
      doc.setTextColor(100)
      const c = output.content
      if (c?.dv && c?.iv) {
        const lines = doc.splitTextToSize(
          `Scatter Plot: ${c.dv} vs ${c.iv}${c.slope != null ? `\nRegression: ${c.dv} = ${c.intercept?.toFixed(2)} + ${c.slope.toFixed(2)} × ${c.iv}` : ''}`,
          pageWidth - 40
        )
        doc.text(lines, 20, currentY)
      } else {
        doc.text('Chart visualization (see application for interactive chart)', 20, currentY)
      }
    }
  }

  // ─── Footer on last page ───
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }

  // Download
  doc.save(`${(projectName || 'report').replace(/[^a-zA-Z0-9]/g, '_')}_report.pdf`)
}

// Simpler version that just exports current output tables
export function generateQuickReport(outputs: OutputItem[], projectName?: string) {
  generatePDFReport({
    title: 'Statistical Analysis Report',
    author: 'TheOneWayGDAGDA',
    outputs,
    projectName,
  })
}
